import { StyleSheet } from "@react-pdf/renderer";

export const COLORS = {
  BRAND: "#071a33",
  ACCENT: "#f5a623",
  BLUE: "#2563eb",
  INK: "#111827",
  MUTED: "#64748b",
  SOFT: "#f8fafc",
  PANEL: "#eef2f7",
  BORDER: "#d8dee8",
  WHITE: "#ffffff",
};

export const styles = StyleSheet.create({
  page: {
    fontFamily: "DM Sans",
    fontSize: 9.5,
    color: COLORS.INK,
    backgroundColor: COLORS.WHITE,
    padding: "28 32 40",
  },

  header: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingBottom: 18,
    borderBottomWidth: 1,
    borderBottomColor: COLORS.BORDER,
  },
  brandBlock: { flex: 1 },
  logo: { width: 150, height: 50, marginBottom: 6 },
  brandFallback: {
    fontSize: 16,
    fontWeight: 700,
    color: COLORS.BRAND,
    marginBottom: 3,
  },
  brandTagline: { color: COLORS.MUTED, fontSize: 8 },
  headerRight: { alignItems: "flex-end" },
  headerTitle: {
    fontSize: 18,
    fontWeight: 700,
    color: COLORS.BRAND,
    letterSpacing: 1.4,
    marginBottom: 8,
  },
  statusBadge: {
    borderRadius: 999,
    padding: "4 9",
    backgroundColor: "#eaf2ff",
    color: COLORS.BLUE,
    fontSize: 7,
    fontWeight: 700,
    letterSpacing: 0.8,
  },

  metaGrid: {
    flexDirection: "row",
    marginTop: 18,
    gap: 10,
  },
  metaCard: {
    flex: 1,
    padding: 10,
    backgroundColor: COLORS.SOFT,
    borderWidth: 1,
    borderColor: COLORS.BORDER,
    borderRadius: 4,
  },
  metaLabel: {
    color: COLORS.MUTED,
    fontSize: 6.8,
    fontWeight: 700,
    letterSpacing: 1.2,
    textTransform: "uppercase",
    marginBottom: 4,
  },
  metaValue: { color: COLORS.INK, fontSize: 10.5, fontWeight: 700 },
  metaSubValue: { color: COLORS.MUTED, fontSize: 8, marginTop: 2 },

  summaryRow: {
    flexDirection: "row",
    marginTop: 16,
    gap: 14,
  },
  partyCard: {
    flex: 1,
    padding: 13,
    borderWidth: 1,
    borderColor: COLORS.BORDER,
    borderRadius: 4,
  },
  partyCardStrong: {
    backgroundColor: COLORS.BRAND,
    borderColor: COLORS.BRAND,
  },
  partyLabel: {
    fontSize: 7,
    fontWeight: 700,
    letterSpacing: 1.4,
    color: COLORS.MUTED,
    marginBottom: 8,
  },
  partyLabelStrong: { color: "#b8c6d8" },
  partyName: { fontSize: 13, fontWeight: 700, color: COLORS.INK, marginBottom: 4 },
  partyNameStrong: { color: COLORS.WHITE },
  partyDetail: { fontSize: 8.2, color: COLORS.MUTED, lineHeight: 1.4 },
  partyDetailStrong: { color: "#d8e3f2" },

  sectionTitle: {
    fontSize: 8,
    color: COLORS.BRAND,
    fontWeight: 700,
    letterSpacing: 1.2,
    marginTop: 20,
    marginBottom: 8,
  },
  table: {
    borderWidth: 1,
    borderColor: COLORS.BORDER,
    borderRadius: 4,
    overflow: "hidden",
  },
  tableHeader: {
    flexDirection: "row",
    backgroundColor: COLORS.BRAND,
    padding: "8 10",
  },
  tableHeaderText: {
    color: COLORS.WHITE,
    fontSize: 7.5,
    fontWeight: 700,
    letterSpacing: 0.8,
  },
  tableRow: {
    flexDirection: "row",
    padding: "9 10",
    borderBottomWidth: 1,
    borderBottomColor: COLORS.BORDER,
    minHeight: 31,
  },
  tableRowAlt: { backgroundColor: COLORS.SOFT },
  itemDesc: { fontSize: 9.4, color: COLORS.INK, fontWeight: 700 },
  itemDetail: { fontSize: 7.7, color: COLORS.MUTED, marginTop: 3 },
  colDescription: { flex: 4 },
  colUnits: { flex: 1, textAlign: "right" },
  colRate: { flex: 1, textAlign: "right" },
  colAmount: { flex: 1.35, textAlign: "right" },

  totalsArea: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginTop: 14,
    gap: 18,
  },
  paymentBox: {
    flex: 1.25,
    padding: 12,
    backgroundColor: COLORS.SOFT,
    borderWidth: 1,
    borderColor: COLORS.BORDER,
    borderRadius: 4,
  },
  paymentTitle: {
    fontSize: 8,
    color: COLORS.BRAND,
    fontWeight: 700,
    letterSpacing: 1,
    marginBottom: 7,
  },
  paymentText: {
    fontSize: 8,
    color: COLORS.MUTED,
    lineHeight: 1.45,
    marginBottom: 3,
  },
  paymentMethodsRow: {
    flexDirection: "row",
    gap: 10,
    marginTop: 8,
  },
  bankDetailsBox: {
    flex: 1,
    paddingTop: 8,
    borderTopWidth: 1,
    borderTopColor: COLORS.BORDER,
  },
  bankDetailsText: {
    fontSize: 7.5,
    color: COLORS.INK,
    lineHeight: 1.35,
    marginBottom: 2,
  },
  qrBox: {
    width: 70,
    alignItems: "center",
    paddingTop: 8,
    borderTopWidth: 1,
    borderTopColor: COLORS.BORDER,
  },
  qrImage: {
    width: 58,
    height: 58,
    objectFit: "contain",
    borderWidth: 1,
    borderColor: COLORS.BORDER,
  },
  qrLabel: {
    marginTop: 3,
    fontSize: 6.5,
    color: COLORS.MUTED,
    textAlign: "center",
  },
  totalsBox: { width: 210 },
  totalLine: {
    flexDirection: "row",
    justifyContent: "space-between",
    padding: "5 0",
    borderBottomWidth: 1,
    borderBottomColor: COLORS.BORDER,
  },
  totalLabel: { color: COLORS.MUTED, fontSize: 8.5 },
  totalValue: { color: COLORS.INK, fontSize: 8.5, fontWeight: 700 },
  amountDue: {
    marginTop: 6,
    padding: "10 12",
    backgroundColor: COLORS.BRAND,
    borderRadius: 4,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  amountDueLabel: {
    color: COLORS.WHITE,
    fontSize: 8,
    fontWeight: 700,
    letterSpacing: 1,
  },
  amountDueValue: {
    color: COLORS.ACCENT,
    fontSize: 13,
    fontWeight: 700,
  },

  notesBox: {
    marginTop: 12,
    padding: 11,
    borderWidth: 1,
    borderColor: "#fde2a7",
    backgroundColor: "#fffbeb",
    borderRadius: 4,
  },
  notesTitle: {
    fontSize: 8,
    fontWeight: 700,
    color: COLORS.BRAND,
    letterSpacing: 1,
    marginBottom: 5,
  },
  noteItem: { fontSize: 8, color: COLORS.MUTED, marginBottom: 3 },

  signaturesRow: {
    flexDirection: "row",
    marginTop: 28,
    gap: 32,
  },
  sigBlock: { flex: 1, alignItems: "center" },
  sigLine: {
    borderTopWidth: 1,
    borderTopColor: COLORS.BORDER,
    width: "100%",
    marginBottom: 5,
  },
  sigLabel: { fontSize: 7.5, color: COLORS.MUTED },

  footer: {
    position: "absolute",
    bottom: 18,
    left: 32,
    right: 32,
    borderTopWidth: 1,
    borderTopColor: COLORS.BORDER,
    paddingTop: 7,
  },
  footerText: {
    fontSize: 7,
    color: COLORS.MUTED,
    textAlign: "center",
  },
});
